name: "octodns-sync-action"
description: "Sync DNS configuration to a cloud DNS provider using OctoDNS"
inputs:
  octodns_config_file:
    description: "OctoDNS config file path, relative to the root of your repo."
    required: true
  doit:
    description: "Analogous to octodns-sync's --doit flag. If false, no changes are made."
    default: "false"
    required: false
  post_pr_comment:
    description: "If true, post output to PR."
    default: "false"
    required: false
  github_token:
    description: "GitHub API Token for Actions."
    required: false
runs:
  using: "docker"
  image: "docker://ghcr.io/cfunkhouser/octodns-sync-action:v0.0.15"
  env:
    GITHUB_TOKEN: ${{ inputs.github_token }}
  args:
    - ${{ inputs.octodns_config_file }}
    - "--doit"
    - "${{ inputs.doit }}"
    - "--post_pr_comment"
    - "${{ inputs.post_pr_comment }}"
