name: "octodns-sync-action"
description: "Sync DNS configuration to a cloud DNS provider using OctoDNS"
inputs:
  octodns_config_file:
    description: "OctoDNS config file path, relative to the root of your repo."
    required: true
  doit:
    description: "Analogous to octodns-sync's --doit flag. If false, no changes are made."
    default: "false"
    required: false
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.octodns_config_file }}
    - "--doit"
    - "${{ inputs.doit }}"
